### ISSUE TITLE
[TODO] MuseUI 2.0 正式版发布计划

### ISSUE THREAD

**Issue by myronliu347** [museui/muse-ui#317]
过完年回来就一直想发正式版，无奈这些天的状态实在是差，实在是提不起兴致来写代码，所以正式发布的计划一直拖到现在才写，希望搭建可以见谅。
正式版发布，需要完成以下：

* [x] 项目升级到webpack2
* [x] 修复现有的所有bug #309 #305 #298 #300 （有一部分的bug我已经修复了，只是没有发版）
* [x] 重写tabs组件 #97  (API基本保持不变，主要是这个组件的功能需要增强) 
* [x] 改善其它组件 (textField, table。。。)
* [x] 文档的优化和补充 （主要增加FAQ文档，然后优化使用文档）

除此之外，muse-ui的默认主题和 logo也会有所改变。

**Comment by breadlesscode** [comment]
No English =(

**Comment by altjz** [comment]
越来越喜欢muse-ui了，加油!

**Comment by duyishuaixue** [comment]
挺不错，阳仔加油！

**Comment by bairdweng** [comment]
牛b，加油！

**Comment by jjjachyty** [comment]
mu-picker的这个问题修改发布了吗？
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value" 
(found in <PickerSlot>)

**Comment by jjjachyty** [comment]
mu-picker的字体和高度可以给个选项设置吗？一般都是字体是14 mu-picker的是18

**Comment by myronliu347** [comment]
@jjjachyty 没有这个问题，是使用上出错的
